export const environment = {
  production: true,
  API_KEY: 'M9oudt0Y.CslR5xOFQkmPPzi3oBbNNcih8MwPLL5h',
  apiUrl: 'http://api:9123/saas_api',
  WEBSOCKET_PROTOCOL: "ws",
  WEBSOCKET_URL: 'api:9123/saas_ws',
  LOCALSTORAGE_TOKEN_INFO_KEY: 'TOKEN_INFO',
  FEEDBACK_USER_ID: 1,
  PUBLIC_ORIGIN: 'http://localhost:9127',
  // apiUrl: 'https://demo.brainhub.co/saas_api',
  // WEBSOCKET_PROTOCOL: "wss",
  // WEBSOCKET_URL: 'demo.brainhub.co/saas_ws',
  // LOCALSTORAGE_TOKEN_INFO_KEY: 'TOKEN_INFO',
  // FEEDBACK_USER_ID: 1,
  // PUBLIC_ORIGIN: 'http://demo.brainhub.co/saas_web',
};
